baseURL = "https://claydugo.com"
title = "Clay Dugo"
theme = "hugo-coder"
languageCode = "en-us"
staticDir = "static"
enableEmoji = true
enableRobotsTXT = true
# wasn't working with theme
# googleAnalytics = "G-S6LK5FZPP4"
googleAnalytics = "UA-146318863-1"

[params]
	author = "Clay Dugo"
	# info = ""
	description = "Clay Dugo's blog and portfolio. Website is open source, click on the commit hash found in the footer to be taken to its github page."
	keywords = "blog, developer, personal, portfolio, python, open source"
	favicon_32 = "/img/favicon-16x16.png"
	favicon_16 = "/img/favicon-32x32.png"
	avatarurl = "/img/pp.png"
	# footercontent = "<a href=\"https://hmmst.claydugo.com\">Uptime</a>"
	hideCredits = true
  hideCopyright = true
  commit = "https://github.com/claydugo/claydugo.com/tree/" 
  custom_css = ["css/stylesheet.css"]

[[params.social]]
    name = "Github"
    icon = "fab fa-github"
    weight = 1
    url = "https://github.com/claydugo/"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    weight = 2
    url = "https://www.linkedin.com/in/claydugo/"
[[params.social]]
    name = "Untappd"
    icon = "fab fa-untappd"
    weight = 3
    url = "https://untappd.com/user/claydugo/"
[[params.social]]
    name = "IMDb"
    icon = "fab fa-imdb"
    weight = 4
    url = "https://www.imdb.com/user/ur84423387"
[[params.social]]
    name = "Keybase"
    icon = "fab fa-keybase"
    weight = 5
    url = "https://keybase.io/dugo"
[[params.social]]
    name = "Goodreads"
    icon = "fab fa-goodreads"
    weight = 6
    url = "https://goodreads.com/claydugo"

# Menu links
[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "/blog/"
[[menu.main]]
    name = "Beer Map"
    weight = 2
    url = "/beermap"

# Blog Params
[permalinks]
    posts = "/:year/:month/:slug/"
    page = "/:slug/"

# Google Analytics
[privacy]
    [privacy.googleAnalytics]
        anonymizeIP = true
        respectDoNotTrack = true
        useSessionStorage = true
