[build]
publish = "public"
command = "GIT_COMMIT_SHA=\"$(git rev-parse --verify HEAD)\" GIT_COMMIT_SHA_SHORT=\"$(git rev-parse --short HEAD)\" hugo --gc --minify"

[context.production.environment]
HUGO_VERSION = "0.57.2"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.split1]
command = "GIT_COMMIT_SHA=\"$(git rev-parse --verify HEAD)\" GIT_COMMIT_SHA_SHORT=\"$(git rev-parse --short HEAD)\" hugo --gc --minify --enableGitInfo"

[context.split1.environment]
HUGO_VERSION = "0.57.2"
HUGO_ENV = "production"

[context.deploy-preview]
command = "GIT_COMMIT_SHA=\"$(git rev-parse --verify HEAD)\" GIT_COMMIT_SHA_SHORT=\"$(git rev-parse --short HEAD)\" hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.57.2"

[context.branch-deploy]
command = "GIT_COMMIT_SHA=\"$(git rev-parse --verify HEAD)\" GIT_COMMIT_SHA_SHORT=\"$(git rev-parse --short HEAD)\" hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "รง"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"

[[redirects]]
    from = "https://claydugo.netlify.com/*"
    to = "https://claydugo.com/"
    status = 301
    force = true
