[build]
publish = "public"

[context.production.environment]
HUGO_VERSION = "0.57.2"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.split1.environment]
HUGO_VERSION = "0.57.2"
HUGO_ENV = "production"

[context.deploy-preview.environment]
HUGO_VERSION = "0.57.2"

[context.branch-deploy.environment]
HUGO_VERSION = "รง"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"

[[redirects]]
    from = "https://claydugo.netlify.com/*"
    to = "https://claydugo.com/"
    status = 301
    force = true
